
'use client';

import React, { useState } from 'react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { Loader2, Mic } from 'lucide-react';
import { toast } from '@/hooks/use-toast';
import { textToSpeech, TextToSpeechOutput } from '@/ai/flows/text-to-speech';

export default function VoiceNotesView() {
    const [text, setText] = useState('Hello! This is a voice note generated by artificial intelligence.');
    const [audioData, setAudioData] = useState<TextToSpeechOutput | null>(null);
    const [isLoading, setIsLoading] = useState(false);

    const handleGenerateAudio = async () => {
        if (!text.trim()) return;
        setIsLoading(true);
        setAudioData(null);
        try {
            const result = await textToSpeech(text);
            setAudioData(result);
        } catch (error) {
            console.error(error);
            toast({ variant: 'destructive', title: 'Error', description: 'Could not generate audio.' });
        } finally {
            setIsLoading(false);
        }
    };

    return (
        <Card>
            <CardHeader>
                <CardTitle>Voice Notes</CardTitle>
                <CardDescription>Convert text into a shareable audio clip using AI.</CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
                <Textarea 
                    placeholder="Enter the text you want to convert to speech..."
                    value={text}
                    onChange={(e) => setText(e.target.value)}
                    rows={4}
                    disabled={isLoading}
                />
                <Button onClick={handleGenerateAudio} disabled={isLoading} className="w-full">
                    {isLoading ? <Loader2 className="h-5 w-5 animate-spin" /> : <><Mic className="mr-2 h-5 w-5" /> Generate Audio</>}
                </Button>

                {isLoading && (
                    <div className="flex justify-center items-center py-4">
                        <Loader2 className="h-8 w-8 animate-spin text-primary"/>
                    </div>
                )}

                {audioData?.media && (
                    <div className="pt-4">
                        <h3 className="font-semibold mb-2">Listen to your note:</h3>
                        <audio controls src={audioData.media} className="w-full">
                            Your browser does not support the audio element.
                        </audio>
                    </div>
                )}
            </CardContent>
        </Card>
    );
}
